"""Phase 14 — Artifact OS: Native XLSX (SpreadsheetML) Exporter.

Produces valid Microsoft Excel (.xlsx) spreadsheets in pure Python without external dependencies.
"""
from __future__ import annotations

import io
import xml.sax.saxutils as sax
import zipfile
from typing import Any

from ..document_ast import (
    DocumentAST,
    SheetNode,
    TableNode,
)
from ..models import ArtifactFormat
from .base import BaseExporter


def _escape(text: str) -> str:
    return sax.escape(str(text))


def _col_name(n: int) -> str:
    """Convert 0-indexed column number to Excel column name (0 -> A, 25 -> Z, 26 -> AA)."""
    result = ""
    n += 1
    while n > 0:
        n, remainder = divmod(n - 1, 26)
        result = chr(65 + remainder) + result
    return result


XLSX_RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>"""

XLSX_STYLES = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <fonts count="2">
    <font><sz val="11"/><name val="Calibri"/></font>
    <font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font>
  </fonts>
  <fills count="3">
    <fill><patternFill patternType="none"/></fill>
    <fill><patternFill patternType="gray125"/></fill>
    <fill><patternFill patternType="solid"><fgColor rgb="FF2563EB"/></patternFill></fill>
  </fills>
  <borders count="2">
    <border><left/><right/><top/><bottom/></border>
    <border>
      <left style="thin"><color auto="1"/></left>
      <right style="thin"><color auto="1"/></right>
      <top style="thin"><color auto="1"/></top>
      <bottom style="thin"><color auto="1"/></bottom>
    </border>
  </borders>
  <cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>
  <cellXfs count="3">
    <xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>
    <xf numFmtId="0" fontId="1" fillId="2" borderId="1" xfId="0" applyFont="1" applyFill="1" applyBorder="1"/>
    <xf numFmtId="0" fontId="0" fillId="0" borderId="1" xfId="0" applyBorder="1"/>
  </cellXfs>
</styleSheet>"""


class XlsxExporter(BaseExporter):
    """Generates standard Microsoft Excel (.xlsx) workbooks."""

    format = ArtifactFormat.XLSX

    def export(self, doc: DocumentAST, **kwargs: Any) -> bytes:
        sheets = list(doc.sheets)

        # If doc.sheets is empty, synthesize sheet from document tables
        if not sheets:
            table_nodes = [n for n in doc.children if isinstance(n, TableNode)]
            if table_nodes:
                for idx, tbl in enumerate(table_nodes, start=1):
                    headers: list[str] = []
                    if tbl.headers:
                        headers = [c.plain_text for c in tbl.headers.cells]
                    data_rows: list[list[Any]] = []
                    for r in tbl.rows:
                        data_rows.append([c.plain_text for c in r.cells])
                    sheets.append(SheetNode(
                        name=f"Table_{idx}" if idx > 1 else "Data",
                        headers=headers,
                        rows=data_rows,
                    ))

        if not sheets:
            sheets.append(SheetNode(
                name="Sheet1",
                headers=["Title", "Summary"],
                rows=[[doc.title, "Generated by HINAA Artifact OS"]],
            ))

        # Shared strings pool
        shared_strings: list[str] = []
        string_lookup: dict[str, int] = {}

        def get_string_id(s: str) -> int:
            if s not in string_lookup:
                string_lookup[s] = len(shared_strings)
                shared_strings.append(s)
            return string_lookup[s]

        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as zf:
            # 1. Package relationships
            zf.writestr("_rels/.rels", XLSX_RELS)

            # 2. Styles
            zf.writestr("xl/styles.xml", XLSX_STYLES)

            # 3. Worksheets & shared strings collection
            sheet_entries: list[tuple[str, str, str]] = []  # (name, sheet_id, r_id)
            sheet_xmls: list[str] = []

            for idx, sheet in enumerate(sheets, start=1):
                rid = f"rId{idx}"
                sheet_entries.append((sheet.name, str(idx), rid))

                row_xmls: list[str] = []
                row_idx = 1

                # Header row
                if sheet.headers:
                    cell_xmls: list[str] = []
                    for col_idx, h in enumerate(sheet.headers):
                        c_ref = f"{_col_name(col_idx)}{row_idx}"
                        sid = get_string_id(str(h))
                        cell_xmls.append(f'<c r="{c_ref}" t="s" s="1"><v>{sid}</v></c>')
                    row_xmls.append(f'<row r="{row_idx}">{"".join(cell_xmls)}</row>')
                    row_idx += 1

                # Data rows
                for r_data in sheet.rows:
                    cell_xmls = []
                    for col_idx, val in enumerate(r_data):
                        c_ref = f"{_col_name(col_idx)}{row_idx}"
                        # Check numeric
                        if isinstance(val, (int, float)) and not isinstance(val, bool):
                            cell_xmls.append(f'<c r="{c_ref}" s="2"><v>{val}</v></c>')
                        else:
                            val_str = str(val if val is not None else "")
                            # Try parsing float
                            try:
                                num = float(val_str)
                                if "." in val_str:
                                    cell_xmls.append(f'<c r="{c_ref}" s="2"><v>{num}</v></c>')
                                else:
                                    cell_xmls.append(f'<c r="{c_ref}" s="2"><v>{int(num)}</v></c>')
                            except ValueError:
                                sid = get_string_id(val_str)
                                cell_xmls.append(f'<c r="{c_ref}" t="s" s="2"><v>{sid}</v></c>')

                    row_xmls.append(f'<row r="{row_idx}">{"".join(cell_xmls)}</row>')
                    row_idx += 1

                ws_xml = (
                    '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
                    '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">\n'
                    f'  <sheetData>{"".join(row_xmls)}</sheetData>\n'
                    '</worksheet>'
                )
                sheet_xmls.append(ws_xml)
                zf.writestr(f"xl/worksheets/sheet{idx}.xml", ws_xml)

            # 4. Shared Strings XML
            si_elements = "".join(f"<si><t>{_escape(s)}</t></si>" for s in shared_strings)
            shared_strings_xml = (
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
                f'<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="{len(shared_strings)}" uniqueCount="{len(shared_strings)}">\n'
                f'{si_elements}\n'
                '</sst>'
            )
            zf.writestr("xl/sharedStrings.xml", shared_strings_xml)

            # 5. Workbook XML & Workbook relationships
            wb_sheets_xml = "".join(
                f'<sheet name="{_escape(name)}" sheetId="{sid}" r:id="{rid}"/>'
                for name, sid, rid in sheet_entries
            )
            workbook_xml = (
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
                '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" '
                'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">\n'
                f'  <sheets>{wb_sheets_xml}</sheets>\n'
                '</workbook>'
            )
            zf.writestr("xl/workbook.xml", workbook_xml)

            wb_rels = [
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            ]
            for idx in range(1, len(sheets) + 1):
                wb_rels.append(
                    f'  <Relationship Id="rId{idx}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet{idx}.xml"/>'
                )
            wb_rels.append(
                f'  <Relationship Id="rId{len(sheets) + 1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
            )
            wb_rels.append(
                f'  <Relationship Id="rId{len(sheets) + 2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/sharedStrings" Target="sharedStrings.xml"/>'
            )
            wb_rels.append("</Relationships>")
            zf.writestr("xl/_rels/workbook.xml.rels", "\n".join(wb_rels))

            # 6. Content Types XML
            ct_lines = [
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
                '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n'
                '  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n'
                '  <Default Extension="xml" ContentType="application/xml"/>\n'
                '  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>\n'
                '  <Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>\n'
                '  <Override PartName="/xl/sharedStrings.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sharedStrings+xml"/>'
            ]
            for idx in range(1, len(sheets) + 1):
                ct_lines.append(
                    f'  <Override PartName="/xl/worksheets/sheet{idx}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
                )
            ct_lines.append("</Types>")
            zf.writestr("[Content_Types].xml", "\n".join(ct_lines))

        return buf.getvalue()
